# Generated by Django 3.0.1 on 2019-12-29 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('marker', models.CharField(max_length=100)),
                ('date_supplied', models.DateTimeField(blank=True, null=True)),
                ('location_in_lab', models.CharField(max_length=130)),
                ('date_serviced', models.DateTimeField(blank=True, null=True)),
                ('next_service_date', models.DateTimeField(blank=True, null=True)),
                ('date_caliberated', models.DateTimeField(blank=True, null=True)),
                ('next_caliberation_date', models.DateTimeField(blank=True, null=True)),
                ('company_that_serviced', models.CharField(max_length=130)),
                ('company_that_caliberated', models.CharField(max_length=130)),
                ('price', models.FloatField(default=0.0)),
                ('using_personel', models.CharField(max_length=130)),
                ('project', models.CharField(max_length=130)),
                ('data_entry_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
